import { City } from './types';

// Approximate rates relative to USD for demo purposes
export const CURRENCY_RATES: Record<string, number> = {
  USD: 1.0,
  EUR: 0.92,
  GBP: 0.79,
  JPY: 151.5,
  INR: 83.3,
  THB: 36.5,
  SGD: 1.35,
  AUD: 1.52,
  AED: 3.67,
  BRL: 5.05,
  AZN: 1.70,
};

export const POPULAR_CITIES: City[] = [
  // Major International Cities
  { id: 'nyc', name: 'New York', region: 'New York, USA', timezone: 'America/New_York', countryCode: 'US-NY', currencyCode: 'USD', baseTemp: 13 },
  { id: 'lon', name: 'London', region: 'UK', timezone: 'Europe/London', countryCode: 'GB', currencyCode: 'GBP', baseTemp: 11 },
  { id: 'par', name: 'Paris', region: 'France', timezone: 'Europe/Paris', countryCode: 'FR', currencyCode: 'EUR', baseTemp: 12 },
  { id: 'ber', name: 'Berlin', region: 'Germany', timezone: 'Europe/Berlin', countryCode: 'DE', currencyCode: 'EUR', baseTemp: 10 },
  { id: 'gyd', name: 'Baku', region: 'Azerbaijan', timezone: 'Asia/Baku', countryCode: 'AZ', currencyCode: 'AZN', baseTemp: 15 },
  { id: 'del', name: 'New Delhi', region: 'India', timezone: 'Asia/Kolkata', countryCode: 'IN', currencyCode: 'INR', baseTemp: 25 },
  { id: 'bkk', name: 'Bangkok', region: 'Thailand', timezone: 'Asia/Bangkok', countryCode: 'TH', currencyCode: 'THB', baseTemp: 28 },
  { id: 'sgp', name: 'Singapore', region: 'Singapore', timezone: 'Asia/Singapore', countryCode: 'SG', currencyCode: 'SGD', baseTemp: 27 },
  { id: 'tyo', name: 'Tokyo', region: 'Japan', timezone: 'Asia/Tokyo', countryCode: 'JP', currencyCode: 'JPY', baseTemp: 16 },
  { id: 'syd', name: 'Sydney', region: 'Australia', timezone: 'Australia/Sydney', countryCode: 'AU', currencyCode: 'AUD', baseTemp: 18 },
  { id: 'sf', name: 'San Francisco', region: 'California, USA', timezone: 'America/Los_Angeles', countryCode: 'US-CA', currencyCode: 'USD', baseTemp: 14 },
  { id: 'dxb', name: 'Dubai', region: 'UAE', timezone: 'Asia/Dubai', countryCode: 'AE', currencyCode: 'AED', baseTemp: 28 },
  { id: 'sao', name: 'São Paulo', region: 'Brazil', timezone: 'America/Sao_Paulo', countryCode: 'BR', currencyCode: 'BRL', baseTemp: 20 },

  // US States (A-Z)
  { id: 'us-al', name: 'Birmingham', region: 'Alabama, USA', timezone: 'America/Chicago', countryCode: 'US-AL', currencyCode: 'USD', baseTemp: 18 },
  { id: 'us-ak', name: 'Anchorage', region: 'Alaska, USA', timezone: 'America/Anchorage', countryCode: 'US-AK', currencyCode: 'USD', baseTemp: 2 },
  { id: 'us-az', name: 'Phoenix', region: 'Arizona, USA', timezone: 'America/Phoenix', countryCode: 'US-AZ', currencyCode: 'USD', baseTemp: 23 },
  { id: 'us-ar', name: 'Little Rock', region: 'Arkansas, USA', timezone: 'America/Chicago', countryCode: 'US-AR', currencyCode: 'USD', baseTemp: 17 },
  { id: 'us-ca-la', name: 'Los Angeles', region: 'California, USA', timezone: 'America/Los_Angeles', countryCode: 'US-CA', currencyCode: 'USD', baseTemp: 19 },
  { id: 'us-co', name: 'Denver', region: 'Colorado, USA', timezone: 'America/Denver', countryCode: 'US-CO', currencyCode: 'USD', baseTemp: 10 },
  { id: 'us-ct', name: 'Bridgeport', region: 'Connecticut, USA', timezone: 'America/New_York', countryCode: 'US-CT', currencyCode: 'USD', baseTemp: 10 },
  { id: 'us-de', name: 'Wilmington', region: 'Delaware, USA', timezone: 'America/New_York', countryCode: 'US-DE', currencyCode: 'USD', baseTemp: 13 },
  { id: 'us-dc', name: 'Washington', region: 'DC, USA', timezone: 'America/New_York', countryCode: 'US-DC', currencyCode: 'USD', baseTemp: 14 },
  { id: 'us-fl', name: 'Miami', region: 'Florida, USA', timezone: 'America/New_York', countryCode: 'US-FL', currencyCode: 'USD', baseTemp: 25 },
  { id: 'us-ga', name: 'Atlanta', region: 'Georgia, USA', timezone: 'America/New_York', countryCode: 'US-GA', currencyCode: 'USD', baseTemp: 17 },
  { id: 'us-hi', name: 'Honolulu', region: 'Hawaii, USA', timezone: 'Pacific/Honolulu', countryCode: 'US-HI', currencyCode: 'USD', baseTemp: 24 },
  { id: 'us-id', name: 'Boise', region: 'Idaho, USA', timezone: 'America/Boise', countryCode: 'US-ID', currencyCode: 'USD', baseTemp: 11 },
  { id: 'us-il', name: 'Chicago', region: 'Illinois, USA', timezone: 'America/Chicago', countryCode: 'US-IL', currencyCode: 'USD', baseTemp: 11 },
  { id: 'us-in', name: 'Indianapolis', region: 'Indiana, USA', timezone: 'America/Indiana/Indianapolis', countryCode: 'US-IN', currencyCode: 'USD', baseTemp: 11 },
  { id: 'us-ia', name: 'Des Moines', region: 'Iowa, USA', timezone: 'America/Chicago', countryCode: 'US-IA', currencyCode: 'USD', baseTemp: 10 },
  { id: 'us-ks', name: 'Wichita', region: 'Kansas, USA', timezone: 'America/Chicago', countryCode: 'US-KS', currencyCode: 'USD', baseTemp: 13 },
  { id: 'us-ky', name: 'Louisville', region: 'Kentucky, USA', timezone: 'America/Kentucky/Louisville', countryCode: 'US-KY', currencyCode: 'USD', baseTemp: 14 },
  { id: 'us-la', name: 'New Orleans', region: 'Louisiana, USA', timezone: 'America/Chicago', countryCode: 'US-LA', currencyCode: 'USD', baseTemp: 21 },
  { id: 'us-me', name: 'Portland', region: 'Maine, USA', timezone: 'America/New_York', countryCode: 'US-ME', currencyCode: 'USD', baseTemp: 7 },
  { id: 'us-md', name: 'Baltimore', region: 'Maryland, USA', timezone: 'America/New_York', countryCode: 'US-MD', currencyCode: 'USD', baseTemp: 13 },
  { id: 'us-ma', name: 'Boston', region: 'Massachusetts, USA', timezone: 'America/New_York', countryCode: 'US-MA', currencyCode: 'USD', baseTemp: 11 },
  { id: 'us-mi', name: 'Detroit', region: 'Michigan, USA', timezone: 'America/Detroit', countryCode: 'US-MI', currencyCode: 'USD', baseTemp: 10 },
  { id: 'us-mn', name: 'Minneapolis', region: 'Minnesota, USA', timezone: 'America/Chicago', countryCode: 'US-MN', currencyCode: 'USD', baseTemp: 7 },
  { id: 'us-ms', name: 'Jackson', region: 'Mississippi, USA', timezone: 'America/Chicago', countryCode: 'US-MS', currencyCode: 'USD', baseTemp: 18 },
  { id: 'us-mo', name: 'Kansas City', region: 'Missouri, USA', timezone: 'America/Chicago', countryCode: 'US-MO', currencyCode: 'USD', baseTemp: 13 },
  { id: 'us-mt', name: 'Billings', region: 'Montana, USA', timezone: 'America/Denver', countryCode: 'US-MT', currencyCode: 'USD', baseTemp: 8 },
  { id: 'us-ne', name: 'Omaha', region: 'Nebraska, USA', timezone: 'America/Chicago', countryCode: 'US-NE', currencyCode: 'USD', baseTemp: 10 },
  { id: 'us-nv', name: 'Las Vegas', region: 'Nevada, USA', timezone: 'America/Los_Angeles', countryCode: 'US-NV', currencyCode: 'USD', baseTemp: 20 },
  { id: 'us-nh', name: 'Manchester', region: 'New Hampshire, USA', timezone: 'America/New_York', countryCode: 'US-NH', currencyCode: 'USD', baseTemp: 9 },
  { id: 'us-nj', name: 'Newark', region: 'New Jersey, USA', timezone: 'America/New_York', countryCode: 'US-NJ', currencyCode: 'USD', baseTemp: 12 },
  { id: 'us-nm', name: 'Albuquerque', region: 'New Mexico, USA', timezone: 'America/Denver', countryCode: 'US-NM', currencyCode: 'USD', baseTemp: 14 },
  { id: 'us-nc', name: 'Charlotte', region: 'North Carolina, USA', timezone: 'America/New_York', countryCode: 'US-NC', currencyCode: 'USD', baseTemp: 16 },
  { id: 'us-nd', name: 'Fargo', region: 'North Dakota, USA', timezone: 'America/Chicago', countryCode: 'US-ND', currencyCode: 'USD', baseTemp: 6 },
  { id: 'us-oh', name: 'Columbus', region: 'Ohio, USA', timezone: 'America/New_York', countryCode: 'US-OH', currencyCode: 'USD', baseTemp: 11 },
  { id: 'us-ok', name: 'Oklahoma City', region: 'Oklahoma, USA', timezone: 'America/Chicago', countryCode: 'US-OK', currencyCode: 'USD', baseTemp: 16 },
  { id: 'us-or', name: 'Portland', region: 'Oregon, USA', timezone: 'America/Los_Angeles', countryCode: 'US-OR', currencyCode: 'USD', baseTemp: 12 },
  { id: 'us-pa', name: 'Philadelphia', region: 'Pennsylvania, USA', timezone: 'America/New_York', countryCode: 'US-PA', currencyCode: 'USD', baseTemp: 13 },
  { id: 'us-ri', name: 'Providence', region: 'Rhode Island, USA', timezone: 'America/New_York', countryCode: 'US-RI', currencyCode: 'USD', baseTemp: 11 },
  { id: 'us-sc', name: 'Charleston', region: 'South Carolina, USA', timezone: 'America/New_York', countryCode: 'US-SC', currencyCode: 'USD', baseTemp: 19 },
  { id: 'us-sd', name: 'Sioux Falls', region: 'South Dakota, USA', timezone: 'America/Chicago', countryCode: 'US-SD', currencyCode: 'USD', baseTemp: 8 },
  { id: 'us-tn', name: 'Nashville', region: 'Tennessee, USA', timezone: 'America/Chicago', countryCode: 'US-TN', currencyCode: 'USD', baseTemp: 16 },
  { id: 'us-tx', name: 'Houston', region: 'Texas, USA', timezone: 'America/Chicago', countryCode: 'US-TX', currencyCode: 'USD', baseTemp: 21 },
  { id: 'us-ut', name: 'Salt Lake City', region: 'Utah, USA', timezone: 'America/Denver', countryCode: 'US-UT', currencyCode: 'USD', baseTemp: 11 },
  { id: 'us-vt', name: 'Burlington', region: 'Vermont, USA', timezone: 'America/New_York', countryCode: 'US-VT', currencyCode: 'USD', baseTemp: 7 },
  { id: 'us-va', name: 'Virginia Beach', region: 'Virginia, USA', timezone: 'America/New_York', countryCode: 'US-VA', currencyCode: 'USD', baseTemp: 15 },
  { id: 'us-wa', name: 'Seattle', region: 'Washington, USA', timezone: 'America/Los_Angeles', countryCode: 'US-WA', currencyCode: 'USD', baseTemp: 12 },
  { id: 'us-wv', name: 'Charleston', region: 'West Virginia, USA', timezone: 'America/New_York', countryCode: 'US-WV', currencyCode: 'USD', baseTemp: 12 },
  { id: 'us-wi', name: 'Milwaukee', region: 'Wisconsin, USA', timezone: 'America/Chicago', countryCode: 'US-WI', currencyCode: 'USD', baseTemp: 9 },
  { id: 'us-wy', name: 'Cheyenne', region: 'Wyoming, USA', timezone: 'America/Denver', countryCode: 'US-WY', currencyCode: 'USD', baseTemp: 8 },
];

export const INITIAL_CITIES = POPULAR_CITIES.filter(c => c.countryCode.startsWith('US-'));

export const WORK_HOURS_START = 9; // 9 AM
export const WORK_HOURS_END = 18; // 6 PM